### ISSUE TITLE
any plan to make sdk open source？support android？

### ISSUE THREAD

**Issue by lizhongchao13** [SuperMap/s3m-spec#3]

**Comment by pasu** [comment]
Sorry for our poor response.
1 As a specification, it is open source. You can get the details  from the folder 'Specification': https://github.com/SuperMap/s3m-spec/tree/master/Specification
2 We provide the necessary tools to reduce the workload of data conversion in the folder 'S3M_SDK'
3 As a data format, we also support mobile platform such as iOS and Android, in such situation, you should use the correct texture format and compressed type due to the limitation of the mobile OS
